# Basic Site Information
title: Francesco d'Amore  # The title of your website (appears in the browser tab and top of the page)
description: This website contains all relevant information about my work.  # Short description for SEO and meta tags

# Theme Configuration
remote_theme: just-the-docs/just-the-docs  # Theme repository for the site (no need to change if you like this theme)

# Repository URL
github_repo_url: "https://github.com/fdamore95/fdamore95.github.io"  # Link to your GitHub repository for easy access

# Navigation Options
heading_anchors: true  # Enable anchor links for headings (adds deep-linking functionality)
back_to_top: true  # Adds a 'Back to top' button at the bottom of the page
back_to_top_text: "Back to top"  # Customize the text for the 'Back to top' button

# Private color schemes
color_scheme: arctic

# GitHub Edit Link (Footer Option)
gh_edit_link: true  # Show 'Edit this page on GitHub' link in the footer
gh_edit_link_text: "View this content on GitHub"  # Customize the footer link text
gh_edit_repository: "https://github.com/fdamore95/fdamore95.github.io"  # Repository URL for editing
gh_edit_branch: "main"  # The branch your docs are served from (update to 'main' if it's not 'master')
# gh_edit_source: docs  # Uncomment and specify if your docs are in a subfolder (e.g., "docs/")
gh_edit_view_mode: "tree"  # Choose 'tree' to show file structure or 'edit' to open the editor directly

# Plugins
plugins:
  - jekyll-relative-links  # Enables relative links to work properly
  - jekyll-remote-theme  # Allows using remote themes

# Additional Customization (Optional)
search_enabled: true  # Enables a search bar for navigating your site (if supported by the theme)
search_placeholder: "Search..."  # Customize placeholder text in the search bar
logo: "/assets/images/logo.png"  # Add a custom logo (optional, specify the path)
# favicon: "/assets/images/favicon.ico"  # Add a custom favicon (optional, specify the path)

# Just the Docs configuration
just_the_docs:
  custom_css: "assets/css/custom.css" # This is where the compiled SCSS will output